In [16]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://avril:avril@localhost/sakila")
# https://docs.sqlalchemy.org/en/14/core/engines.html

In [17]:
actor = pd.read_sql_query("select * from actor;", engine)

In [18]:
actor

     actor_id first_name     last_name         last_update
0           1   PENELOPE       GUINESS 2006-02-15 04:34:33
1           2       NICK      WAHLBERG 2006-02-15 04:34:33
2           3         ED         CHASE 2006-02-15 04:34:33
3           4   JENNIFER         DAVIS 2006-02-15 04:34:33
4           5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33
..        ...        ...           ...                 ...
201       202         vi            bo 2021-05-06 14:17:02
202       203       STAN        LAUREL 2021-05-24 14:25:28
203       204    OLIVIER         HARDY 2021-05-24 14:26:56
204       205   LEONARDO      DICAPRIO 2021-05-24 14:27:04
205       206       KATE       WINSLET 2021-05-24 14:27:30

[206 rows x 4 columns]

In [33]:
#CrÃ©er une fonction new_customer()qui va permettre 
#lâ€™insertion dâ€™un nouveau client dans la table customer
#en demandant Ã  un utilisateur de saisir les donnÃ©es, 
#ainsi que son adresse pour remplir les tables address, 
#city et country.Faire attention au contrainte dâ€™intÃ©gritÃ©


def new_customer():
    insert into country (country,last_update) values('Cannes',now())
    select * from country where country="Cannes"
    insert into city(city,country_id,last_update) value ('mer',110,now())
    select * from city where city='mer'
    insert into address (address,district,city_id,phone,location,last_update) values ('lili','lolo',602,'0000000000',ST_GeomFromText('POINT(1 -1)'),now())
    
new_customer()

DataError: (pymysql.err.DataError) (1366, "Incorrect integer value: 'avenue' for column 'address_id' at row 1")
[SQL: insert into customer (store_id,first_name,last_name,email,address_id) values ("1","marie","marie","marie@gmail.com","avenue");]
(Background on this error at: http://sqlalche.me/e/13/9h9h)