In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

ratings = pd.read_csv("ratings.csv")
books = pd.read_csv("books.csv")
tags = pd.read_csv("tags.csv")
book_tags = pd.read_csv("book_tags.csv")
to_read = pd.read_csv("to_read.csv")

In [2]:
ratings

         user_id  book_id  rating
0              1      258       5
1              2     4081       4
2              2      260       5
3              2     9296       5
4              2     2318       3
...          ...      ...     ...
5976474    49925      510       5
5976475    49925      528       4
5976476    49925      722       4
5976477    49925      949       5
5976478    49925     1023       4

[5976479 rows x 3 columns]

In [5]:
left_right = pd.merge(ratings, books)

,user_id,book_id,rating,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,258,5,1232,1232,3209783,279,143034901,9.780143e+12,"Carlos Ruiz Zafón, Lucia Graves",...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
1,11,258,3,1232,1232,3209783,279,143034901,9.780143e+12,"Carlos Ruiz Zafón, Lucia Graves",...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
2,143,258,4,1232,1232,3209783,279,143034901,9.780143e+12,"Carlos Ruiz Zafón, Lucia Graves",...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
3,242,258,5,1232,1232,3209783,279,143034901,9.780143e+12,"Carlos Ruiz Zafón, Lucia Graves",...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
4,325,258,4,1232,1232,3209783,279,143034901,9.780143e+12,"Carlos Ruiz Zafón, Lucia Graves",...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5976474,36773,9548,5,30839185,30839185,51437887,4,NaN,NaN,L.J. Shen,...,15460,15482,2179,241,504,1952,5193,7592,https://images.gr-assets.com/books/1481945407m...,https://images.gr-assets.com/books/1481945407s...
5976475,50673,9548,4,30839185,30839185,51437887,4,NaN,NaN,L.J. Shen,...,15460,15482,2179,241,504,1952,5193,7592,https://images.gr-assets.com/books/1481945407m...,https://images.gr-assets.com/books/1481945407s...
5976476,45213,9548,3,30839185,30839185,51437887,4,NaN,NaN,L.J. Shen,...,15460,15482,2179,241,504,1952,5193,7592,https://images.gr-assets.com/books/1481945407m...,https://images.gr-assets.com/books/1481945407s...
5976477,12872,9548,4,30839185,30839185,51437887,4,NaN,NaN,L.J. Shen,...,15460,15482,2179,241,504,1952,5193,7592,https://images.gr-assets.com/books/1481945407m...,https://images.gr-assets.com/books/1481945407s...
5976478,46353,9548,5,30839185,30839185,51437887,4,NaN,NaN,L.J. Shen,...,15460,15482,2179,241,504,1952,5193,7592,https://images.gr-assets.com/books/1481945407m...,https://images.gr-assets.com/books/1481945407s...

In [7]:
tags

       tag_id    tag_name
0           0           -
1           1        --1-
2           2       --10-
3           3       --12-
4           4      --122-
...       ...         ...
34247   34247   Ｃhildrens
34248   34248   Ｆａｖｏｒｉｔｅｓ
34249   34249       Ｍａｎｇａ
34250   34250      ＳＥＲＩＥＳ
34251   34251  ｆａｖｏｕｒｉｔｅｓ

[34252 rows x 2 columns]

In [9]:
triple = pd.merge(left_right, tags,left_on="user_id", right_on="tag_id")
triple

,user_id,book_id,rating,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,...,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,tag_id,tag_name
0,1,258,5,1232,1232,3209783,279,143034901,9.780143e+12,"Carlos Ruiz Zafón, Lucia Graves",...,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...,1,--1-
1,1,33,4,930,929,1558965,220,739326228,9.780739e+12,Arthur Golden,...,25605,23500,59033,258700,517157,559782,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...,1,--1-
2,1,70,5,375802,375802,2422333,224,812550706,9.780813e+12,Orson Scott Card,...,38054,15330,27612,103439,264207,462829,https://images.gr-assets.com/books/1408303130m...,https://images.gr-assets.com/books/1408303130s...,1,--1-
3,1,103,3,7126,7126,391568,1310,140449264,9.780140e+12,"Alexandre Dumas, Robin Buss",...,15925,10381,22482,89980,183142,295235,https://images.gr-assets.com/books/1309203605m...,https://images.gr-assets.com/books/1309203605s...,1,--1-
4,1,255,1,662,662,817219,147,452011876,9.780452e+12,"Ayn Rand, Leonard Peikoff",...,14666,30901,27442,53762,78744,105796,https://images.gr-assets.com/books/1405868167m...,https://images.gr-assets.com/books/1405868167s...,1,--1-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3908002,26469,4804,5,25564446,25564446,45362463,26,NaN,NaN,Brittainy C. Cherry,...,4123,907,1248,4590,9980,16644,https://images.gr-assets.com/books/1441375261m...,https://images.gr-assets.com/books/1441375261s...,26469,safe-side
3908003,26469,7772,4,26252659,26252659,46249382,15,692572031,9.780693e+12,Lauren Blakely,...,2363,340,1081,4307,7531,6824,https://images.gr-assets.com/books/1485375190m...,https://images.gr-assets.com/books/1485375190s...,26469,safe-side
3908004,26469,4752,5,28477789,28477789,48619088,13,NaN,NaN,"Vi Keeland, Penelope Ward",...,3250,537,1283,4891,11325,13587,https://images.gr-assets.com/books/1456315337m...,https://images.gr-assets.com/books/1456315337s...,26469,safe-side
3908005,26469,9913,4,25912358,25912358,45800086,19,NaN,NaN,Tillie Cole,...,3018,440,708,1604,2816,8317,https://images.gr-assets.com/books/1453299050m...,https://images.gr-assets.com/books/1453299050s...,26469,safe-side
3908006,26469,6289,4,29610595,29610595,49952105,5,NaN,NaN,Colleen Hoover,...,2980,572,1233,3654,6596,8404,https://images.gr-assets.com/books/1459520906m...,https://images.gr-assets.com/books/1459520906s...,26469,safe-side